[package]
name = "pwfind"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
colored = "3.1.1"
flate2 = "1.1.9"
ignore = "0.4.25"
rayon = "1.11.0"
regex = "1.12.3"
